# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'message.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(300, 200)
        Dialog.setMinimumSize(QtCore.QSize(300, 200))
        Dialog.setMaximumSize(QtCore.QSize(300, 200))
        self.pushButton_ok = QtWidgets.QPushButton(Dialog)
        self.pushButton_ok.setGeometry(QtCore.QRect(0, 140, 300, 61))
        font = QtGui.QFont()
        font.setFamily("Source Han Sans CN")
        font.setPointSize(13)
        self.pushButton_ok.setFont(font)
        self.pushButton_ok.setStyleSheet("QPushButton{\n"
"border:none;\n"
"background-color: rgb(115, 210, 22);\n"
"color:rgb(255, 255, 255)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgba(115, 210, 22, 200);\n"
"}")
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(50, 30, 200, 81))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "message"))
        self.pushButton_ok.setText(_translate("Dialog", "我知道了"))
